version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/usr/src/app
      - n2l:/usr/src/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENV_MODE=development
    command: streamlit run app.py

volumes:
  n2l:
